import pygame as py
from pygame import Vector2

SCREEN_WIDTH = 1040
SCREEN_HEIGHT = 800
SCREEN_WIDTH_CENTER = SCREEN_WIDTH / 2
SCREEN_HEIGHT_CENTER = SCREEN_HEIGHT / 2

DEFUALT_GRAVITY = 8
DEFAULT_MAX_VELOCITY_X = 60
DEFAULT_MAX_VELOCITY_Y = 60
DEFAULT_FRICTION = Vector2(.09, 0)
VELOCITY_THRESHOLD = 0.1

PIXELS_PER_UNIT = 50

SCREEN = None

def INIT_DISPLAY():
    global SCREEN
    if SCREEN is None:
        SCREEN = py.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    return SCREEN